
package GUI;

import ConnectDB.OracleConnection;
import static GUI.TrangChu_KhachHang_fr.MKHHT;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author TIEN NHAN
 */
public class DatVe_fr extends javax.swing.JFrame {

    static String MKHHT=null;
    DefaultTableModel model;
    public ArrayList<String> listmaG = new ArrayList<String>();
    public ArrayList<String> listtenG = new ArrayList<String>();
    public ArrayList<String> listmaLT = new ArrayList<String>();
    /**
     * Creates new form DatVe
     */
    public DatVe_fr() {
        initComponents();
        setVisible(true);
        loadGa();
        this.setLocationRelativeTo(null);
    }
   
    public void set_MKHHT(String a){
        MKHHT=a;            
    }
    
    public void loadGa(){
        OracleConnection OC = new OracleConnection();
        Connection conn = null;
        try{
            conn = OC.getOracleConnection();
            String SQL = "SELECT * FROM GA";
            Statement pres = conn.createStatement();
            ResultSet rs = pres.executeQuery(SQL);
            while(rs.next()){
                listmaG.add(rs.getString("maGa"));
                listtenG.add(rs.getString("TenGa"));
            }
            jComboBox1.setModel(new DefaultComboBoxModel(listtenG.toArray()));
            jComboBox2.setModel(new DefaultComboBoxModel(listtenG.toArray()));
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbmaKH = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(51, 204, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 102, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 69, 171, -1));

        jLabel1.setBackground(new java.awt.Color(255, 102, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ga khởi hành:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 73, 133, -1));

        jLabel2.setBackground(new java.awt.Color(255, 102, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Ga đến:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 73, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(51, 204, 255));
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 102, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 69, 156, -1));

        jDateChooser1.setForeground(new java.awt.Color(0, 255, 255));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 211, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Thời gian khởi hành:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 194, 29));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Xem thông tin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 172, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        lbmaKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(lbmaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 6, 79, 26));

        jLabel4.setBackground(new java.awt.Color(255, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PIC_ICON/nen_all.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 780, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals(jComboBox2.getSelectedItem())){
            JOptionPane.showMessageDialog(null, "Ga khởi hành và ga kết thúc không được giống nhau!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(jDateChooser1.getDate()==null){
            JOptionPane.showMessageDialog(null, "Bạn cần chọn ngày!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Date date=new java.sql.Date(System.currentTimeMillis());
        System.out.println(date);
        Date date2 = new java.sql.Date(jDateChooser1.getDate().getTime());
        if(date2.compareTo(date) < 0){
            JOptionPane.showMessageDialog(null, "Ngày chọn không được nhỏ hơn ngày hiện tại!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        System.out.println(new java.sql.Date(jDateChooser1.getDate().getTime()).toString().substring(0, 4));
        System.out.println(new java.sql.Date(jDateChooser1.getDate().getTime()).toString().substring(5, 7));
        System.out.println(new java.sql.Date(jDateChooser1.getDate().getTime()).toString().substring(8, 10));
        ThongTinGheDat_fr ghe = new ThongTinGheDat_fr();
        ghe.set_MKHHT(MKHHT);
        DefaultTableModel lichtrinh = (DefaultTableModel) ghe.gettbLichTrinh().getModel();
        OracleConnection OC = new OracleConnection();
        Connection conn = null;
        try{
            conn = OC.getOracleConnection();
            String SQL1 = "SELECT LICHTRINH.maLT, LICHTRINH.MATAU, TGIANKH, TAU.LOAITAU, TENTAU, COUNT(CTVE.MAGHE) AS TONGGHE FROM TAU INNER JOIN LICHTRINH ON TAU.MATAU=LICHTRINH.MATAU LEFT JOIN VE ON LICHTRINH.MALT = VE.MALT LEFT JOIN CTVE ON VE.MAVE = CTVE.MAVE \n"
                    + "WHERE EXTRACT (YEAR FROM TGIANKH) = ? AND EXTRACT (MONTH FROM TGIANKH) = ? AND EXTRACT (DAY FROM TGIANKH) = ? AND GAKH = ? AND GAKT = ?"
                    + "GROUP BY LICHTRINH.maLT, LICHTRINH.MATAU, TGIANKH, TAU.LOAITAU, TENTAU";
            PreparedStatement pres1 = conn.prepareStatement(SQL1);
            pres1.setInt(1, Integer.parseInt(new java.sql.Date(jDateChooser1.getDate().getTime()).toString().substring(0, 4)));
            pres1.setInt(2, Integer.parseInt(new java.sql.Date(jDateChooser1.getDate().getTime()).toString().substring(5, 7)));
            pres1.setInt(3, Integer.parseInt(new java.sql.Date(jDateChooser1.getDate().getTime()).toString().substring(8, 10)));
            pres1.setString(4, listmaG.get(jComboBox1.getSelectedIndex()));
            pres1.setString(5, listmaG.get(jComboBox2.getSelectedIndex()));
            ResultSet rs1 = pres1.executeQuery();
            while(rs1.next()){
                listmaLT.add(rs1.getString("maLT"));
                ghe.listmaLT(rs1.getString("maLT"));
                String malt = rs1.getString("maLT");
                String magkh = jComboBox1.getSelectedItem().toString();
                String magkt = jComboBox2.getSelectedItem().toString();
                String matau = rs1.getString("MATAU");
                ghe.listmaTau(matau);
                String tentau = rs1.getString("TENTAU");
                String ltau = "";
                int loaitau = rs1.getInt("LOAITAU");
                switch(loaitau){
                    case 1:
                        ltau = "Bình dân";
                        break;
                    case 2:
                        ltau = "Cao cấp";
                        break;
                    case 3:
                        ltau = "Thương gia";
                        break;
                }
                Date nkh = rs1.getDate("TGIANKH");
                Time gkh = rs1.getTime("TGIANKH");
                int tongghe = 9 - rs1.getInt("TONGGHE");
                ghe.tongGheChChon(tongghe);
                lichtrinh.addRow(new Object[] {malt,magkh,magkt,tentau,ltau,nkh,gkh,tongghe});
            }
        }catch (Exception e){
            e.printStackTrace();
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        if(MKHHT==null){
            new TrangChu_Admin_fr();
        } else{
            TrangChu_KhachHang_fr a = new TrangChu_KhachHang_fr();
            a.set_MKHHT(MKHHT);
            a.getAccount().setText(MKHHT);
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatVe_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatVe_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatVe_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatVe_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatVe_fr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbmaKH;
    // End of variables declaration//GEN-END:variables
}
