/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ConnectDB.OracleConnection;
import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Time;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khoan
 */
public class QLGa extends javax.swing.JFrame {

    DefaultTableModel listGa;

    /**
     * Creates new form QLGa
     */
    public QLGa() {
        initComponents();
        listGa = (DefaultTableModel) tbga.getModel();
        LoadGa();
        setVisible(true);
    }
    
    public String getmaGa(){
        String maGa = "";
        OracleConnection OC = new OracleConnection();
        Connection conn = null;
        try{
            conn = OC.getOracleConnection();
            conn.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
            conn.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
            String SQL1 = "SELECT MAGA FROM GA ORDER BY MAGA DESC";
            Statement pres1 = conn.createStatement();
            ResultSet rs1 = pres1.executeQuery(SQL1);
            if(rs1.next()==false){
                maGa = "GA01";
            } int MThientai = Integer.parseInt(rs1.getString(1).substring(3,rs1.getString(1).length()-1)) + 1;
                
                if (MThientai < 10){
                    maGa = "GA0" + MThientai;
                } else 
                    maGa = "GA" + MThientai; 
                      
        }
        catch (Exception e){
            e.printStackTrace();
        }
        return maGa;
    }
        public void LoadGa(){
        listGa.setRowCount(0);
        OracleConnection OC = new OracleConnection();
        Connection conn = null;
        try{
            conn = OC.getOracleConnection();
            conn.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
            conn.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
            String SQL = "SELECT * FROM GA ORDER BY MAGA ASC";
            
            Statement pres = conn.createStatement();
            
            ResultSet rs = pres.executeQuery(SQL);
            
            while(rs.next()){
                String r1 = rs.getString("MAGA");
                String r2 = rs.getString("TENGA");
                Object row[] = new Object[] {r1,r2};
                listGa.addRow(row);
            }
            conn.close();
            pres.close();
            rs.close();
            
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbga = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTraCuu = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        maga_txt = new javax.swing.JTextField();
        sua_bt = new javax.swing.JButton();
        xoa_bt = new javax.swing.JButton();
        them_bt = new javax.swing.JButton();
        tenga_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý ga");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbga.setBackground(new java.awt.Color(51, 255, 255));
        tbga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Ga", "Tên Ga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbgaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbga);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 176, -1, 302));

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 511, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Danh sách ga tàu");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 51), 1, true));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 190, 36));
        getContentPane().add(txtTraCuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 129, 203, -1));

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 204, 102));
        jButton3.setText("Tra cứu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 128, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));

        maga_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        maga_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maga_txt.setEnabled(false);

        sua_bt.setBackground(new java.awt.Color(102, 255, 255));
        sua_bt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        sua_bt.setForeground(new java.awt.Color(255, 0, 102));
        sua_bt.setText("Sửa");
        sua_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua_btActionPerformed(evt);
            }
        });

        xoa_bt.setBackground(new java.awt.Color(102, 255, 255));
        xoa_bt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        xoa_bt.setForeground(new java.awt.Color(255, 0, 102));
        xoa_bt.setText("Xóa");
        xoa_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoa_btActionPerformed(evt);
            }
        });

        them_bt.setBackground(new java.awt.Color(102, 255, 255));
        them_bt.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        them_bt.setForeground(new java.awt.Color(255, 0, 102));
        them_bt.setText("Thêm");
        them_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên Ga:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("THÔNG TIN GA");

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(them_bt)
                        .addGap(33, 33, 33)
                        .addComponent(xoa_bt)
                        .addGap(30, 30, 30)
                        .addComponent(sua_bt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tenga_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton4))
                            .addComponent(maga_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(maga_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tenga_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them_bt)
                    .addComponent(xoa_bt)
                    .addComponent(sua_bt))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 102));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 128, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PIC_ICON/nen_all.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbgaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbgaMouseClicked
        // TODO add your handling code here:
         int indexTB = tbga.getSelectedRow();
            if(indexTB >=0 && indexTB < tbga.getRowCount())
            {
                maga_txt.setText(listGa.getValueAt(indexTB,0).toString());
                tenga_txt.setText(listGa.getValueAt(indexTB,1).toString());
            }
    }//GEN-LAST:event_tbgaMouseClicked

    private void them_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btActionPerformed
        // TODO add your handling code here:
                
        if (tenga_txt.getText().equals("")
            ){
            JOptionPane.showMessageDialog(rootPane,"Vui lòng điền đầy đủ thông tin", "Thiếu thông tin", HEIGHT);
        }
        else if(maga_txt.getText().equals("") != true
                ){
                JOptionPane.showMessageDialog(rootPane,"Bạn cần reset! ", "Thiếu thông tin", HEIGHT);
        }
        else {
            try {
                Connection conn = OracleConnection.getOracleConnection();
                String SQL_check = "select*from GA where "+"MAGA='"+ maga_txt.getText()+"'";
                String trSQL = "INSERT INTO GA VALUES (?,?)";
                PreparedStatement pre = conn.prepareStatement(SQL_check);
                ResultSet rs = pre.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(rootPane, "Mã ga này đã tồn tại! Hãy chọn chức năng sửa!", "Lỗi!", HEIGHT);
                    tenga_txt.setText("");
                } else {
                    System.out.println("ok");
                    PreparedStatement ps= conn.prepareStatement(trSQL);
                        ps.setString(1, getmaGa());
                        ps.setString(2, tenga_txt.getText());
                    int kq = ps.executeUpdate();
                    if (kq == 1) JOptionPane.showMessageDialog(this,"Thêm thành công!");
                    LoadGa();
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_them_btActionPerformed

    private void xoa_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoa_btActionPerformed
        // TODO add your handling code here:
                        if (tenga_txt.getText().equals("")
                || maga_txt.getText().equals("")
            ){
            JOptionPane.showMessageDialog(rootPane,"Thiếu thông tin! Không thể xóa! Vui lòng chọn thông tin", "Thiếu thông tin", HEIGHT);
            maga_txt.setText("");
            tenga_txt.setText("");
            }       
        else {
            try {
                Connection conn = OracleConnection.getOracleConnection();
                String SQL_check = "select*from GA where MAGA ='" + maga_txt.getText() + "' AND TENGA='"+tenga_txt.getText()+"'";
                String trSQL = "DELETE FROM GA where MAGA=?";
                PreparedStatement pre = conn.prepareStatement(SQL_check);
                ResultSet rs = pre.executeQuery();
                if (rs.next()) 
                {
                    System.out.println("ok");
                    PreparedStatement ps= conn.prepareStatement(trSQL);
                        ps.setString(1, maga_txt.getText());
                    int kq = ps.executeUpdate();
                    if (kq == 1) JOptionPane.showMessageDialog(this,"Xóa thành công!");
                    LoadGa();
                }
                else {
                    JOptionPane.showMessageDialog(rootPane,"Không tìm thấy ga! Vui lòng chọn lại!", "Sai định dạng!", HEIGHT);
                maga_txt.setText("");
                tenga_txt.setText("");
                }
                    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,"Không thể xóa ga vì vi phạm các ràng buộc!", "Lỗi!", HEIGHT);
                e.printStackTrace();
            }
                    
                }
    }//GEN-LAST:event_xoa_btActionPerformed

    private void sua_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sua_btActionPerformed
        // TODO add your handling code here:
        if (tenga_txt.getText().equals("")
            ){
            JOptionPane.showMessageDialog(rootPane,"Vui lòng điền đầy đủ thông tin", "Thiếu thông tin", HEIGHT);
        }
        else if(maga_txt.getText().equals("") == true
                ){
                JOptionPane.showMessageDialog(rootPane,"Bạn cần chọn một ga! ", "Thiếu thông tin", HEIGHT);
        }
        else {
            try {
                Connection conn = OracleConnection.getOracleConnection();
                String trSQL = "UPDATE GA SET TENGA = ? WHERE MAGA LIKE ?";
                PreparedStatement pre = conn.prepareStatement(trSQL);
                pre.setString(1, tenga_txt.getText());
                pre.setString(2, '%'+maga_txt.getText()+'%');
                int rs = pre.executeUpdate();
                if(rs == 1){
                    JOptionPane.showMessageDialog(rootPane,"Sửa thành công", "Thông báo", HEIGHT);
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_sua_btActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TrangChu_Admin_fr();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        listGa = (DefaultTableModel) tbga.getModel();
        listGa.setRowCount(0);
        String tracuu = '%'+txtTraCuu.getText()+'%';
        if(tracuu.equals("")){
            JOptionPane.showMessageDialog(null, "Không có thông tin!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        OracleConnection OC = new OracleConnection();
        Connection conn = null;
        try{
            conn = OC.getOracleConnection();
            String SQL = "SELECT * FROM GA WHERE MAGA LIKE ? OR TENGA LIKE ?";
            PreparedStatement pres = conn.prepareStatement(SQL);
            pres.setString(1, tracuu);
            pres.setString(2, tracuu);
            ResultSet rs = pres.executeQuery();
            while(rs.next()){
                String maga= rs.getString("MAGA");
                String tenga = rs.getString("TENGA");
                listGa.addRow(new Object[] {maga,tenga});
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtTraCuu.setText("");
        listGa.setRowCount(0);
        LoadGa();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        maga_txt.setText("");
        tenga_txt.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLGa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLGa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLGa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLGa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLGa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maga_txt;
    private javax.swing.JButton sua_bt;
    private javax.swing.JTable tbga;
    private javax.swing.JTextField tenga_txt;
    private javax.swing.JButton them_bt;
    private javax.swing.JTextField txtTraCuu;
    private javax.swing.JButton xoa_bt;
    // End of variables declaration//GEN-END:variables
}
