/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ConnectDB.OracleConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khoan
 */
public class QLTau_fr extends javax.swing.JFrame {

    DefaultTableModel listTau;
    /**
     * Creates new form QLTau_fr
     */
    public QLTau_fr() {
        initComponents();

        listTau = (DefaultTableModel) tbtau.getModel();
        LoadTau();
        setVisible(true);
    }
    
    public String getmaTau(){
        String maTau = "";
        OracleConnection OC = new OracleConnection();
        Connection conn = null;
        try{
            conn = OC.getOracleConnection();
            conn.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
            conn.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
            String SQL1 = "SELECT MATAU FROM TAU ORDER BY MATAU DESC";
            Statement pres1 = conn.createStatement();
            ResultSet rs1 = pres1.executeQuery(SQL1);
            if(rs1.next()==false){
                maTau = "TAU01";
            } int MThientai = Integer.parseInt(rs1.getString(1).substring(3,rs1.getString(1).length())) + 1;
                
                if (MThientai < 10){
                    maTau = "TAU0" + MThientai;
                } else 
                    maTau = "TAU" + MThientai; 
                      
        }
        catch (Exception e){
            e.printStackTrace();
        }
        return maTau;
    }
        public void LoadTau(){
        listTau.setRowCount(0);
        OracleConnection OC = new OracleConnection();
        Connection conn = null;
        try{
            conn = OC.getOracleConnection();
            conn.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
            conn.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
            String SQL = "SELECT * FROM TAU ORDER BY MATAU ASC";
            
            Statement pres = conn.createStatement();
            
            ResultSet rs = pres.executeQuery(SQL);
            
            while(rs.next()){
                String r1 = rs.getString("MATAU");
                String r2 = rs.getString("TENTAU");
                String r3 = "" ;
                if(rs.getString("LOAITAU").equals("1")){
                    r3 = "Bình Dân";
                } else if(rs.getString("LOAITAU").equals("2")){
                    r3 = "Cao cấp";
                } else r3 = "Thương gia";
                Object row[] = new Object[] {r1,r2,r3};
                listTau.addRow(row);
            }
            conn.close();
            pres.close();
            rs.close();
            
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tentau_txt = new javax.swing.JTextField();
        loaitau_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtau = new javax.swing.JTable();
        them_bt = new javax.swing.JButton();
        matau_txt = new javax.swing.JTextField();
        sua_bt = new javax.swing.JButton();
        xoa_bt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtTraCuu = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý tàu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("Loại Tàu:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 256, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Tên Tàu:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 219, -1, -1));

        tentau_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tentau_txtActionPerformed(evt);
            }
        });
        getContentPane().add(tentau_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 211, 138, -1));

        loaitau_txt.setToolTipText("1 , 2 or 3");
        loaitau_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaitau_txtActionPerformed(evt);
            }
        });
        getContentPane().add(loaitau_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 252, 138, -1));

        tbtau.setBackground(new java.awt.Color(51, 255, 255));
        tbtau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tàu", "Tên Tàu", "Loại Tàu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbtau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtauMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbtau);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 193, 583, 239));

        them_bt.setBackground(new java.awt.Color(0, 0, 255));
        them_bt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        them_bt.setForeground(new java.awt.Color(255, 0, 51));
        them_bt.setText("Thêm");
        them_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_btActionPerformed(evt);
            }
        });
        getContentPane().add(them_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 397, -1, -1));

        matau_txt.setEnabled(false);
        getContentPane().add(matau_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 176, 138, -1));

        sua_bt.setBackground(new java.awt.Color(0, 0, 255));
        sua_bt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        sua_bt.setForeground(new java.awt.Color(255, 0, 51));
        sua_bt.setText("Sửa");
        sua_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua_btActionPerformed(evt);
            }
        });
        getContentPane().add(sua_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 397, -1, -1));

        xoa_bt.setBackground(new java.awt.Color(0, 0, 255));
        xoa_bt.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        xoa_bt.setForeground(new java.awt.Color(255, 0, 51));
        xoa_bt.setText("Xóa");
        xoa_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoa_btActionPerformed(evt);
            }
        });
        getContentPane().add(xoa_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 397, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 478, -1, -1));

        txtTraCuu.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        getContentPane().add(txtTraCuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 146, 265, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Tra cứu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 146, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 255));
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 146, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("THÔNG TIN TÀU");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 93, 245, 25));

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 341, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quản Lý Tàu");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 93, 130, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("1: Bình dân, 2:Cao cấp, 3: Thương gia");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 308, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PIC_ICON/nen_all.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tentau_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tentau_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tentau_txtActionPerformed

    private void them_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_btActionPerformed
        // TODO add your handling code here:
        if(matau_txt.getText().equals("") != true){
            JOptionPane.showMessageDialog(rootPane,"Vui lòng reset", "Lỗi", HEIGHT);
            return;
        }
        if (!loaitau_txt.getText().matches("-?\\d+")
                 ) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập lại loại tàu!", "Sai định dạng!", HEIGHT);
            loaitau_txt.setText("");
            return;
         }
        if (tentau_txt.getText().equals("")
            ){
            JOptionPane.showMessageDialog(rootPane,"Vui lòng điền đầy đủ thông tin", "Thiếu thông tin", HEIGHT);
        }       
        else {
            try {
                Connection conn = OracleConnection.getOracleConnection();
                String SQL_check = "select*from TAU where "+"MATAU='"+ matau_txt.getText()+"'";
                String trSQL = "INSERT INTO TAU VALUES (?,?,?)";
                PreparedStatement pre = conn.prepareStatement(SQL_check);
                ResultSet rs = pre.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(rootPane, "Mã tàu này đã tồn tại! Hãy chọn chức năng sửa!", "Lỗi!", HEIGHT);
                    tentau_txt.setText("");
                    loaitau_txt.setText("");
                } else {
                    
                    PreparedStatement ps= conn.prepareStatement(trSQL);
                        ps.setString(1, getmaTau());
                        ps.setString(2, tentau_txt.getText());
                        ps.setString(3, loaitau_txt.getText());
                        System.out.println(getmaTau());
                    int kq = ps.executeUpdate();
                    if (kq == 1) JOptionPane.showMessageDialog(this,"Thêm thành công!");
                    LoadTau();
                }

            } catch (Exception e) {
                
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_them_btActionPerformed

    private void sua_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sua_btActionPerformed
        // TODO add your handling code here: 
         
        if (tentau_txt.getText().equals("")
                || loaitau_txt.getText().equals("")
            ){
            JOptionPane.showMessageDialog(rootPane,"Vui lòng điền đầy đủ thông tin", "Thiếu thông tin", HEIGHT);
        }
                else if(matau_txt.getText().equals("")
                ){
                JOptionPane.showMessageDialog(rootPane,"Bạn chưa có "
                        + "mã tàu! Không thể sửa! ", "Thiếu thông tin", HEIGHT);
        }
         else if (!loaitau_txt.getText().matches("-?\\d+")
                 ) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập lại loại tàu (loại tàu phải là một số)!", "Sai định dạng!", HEIGHT);
            loaitau_txt.setText("");
         }
        else {
            try {
                Connection conn = OracleConnection.getOracleConnection();
                String SQL_check = "select*from TAU where MATAU ='" + matau_txt.getText() + "'";
                String trSQL = "UPDATE TAU SET  TENTAU=?, LOAITAU=? where MATAU='"+matau_txt.getText()+"'";
                PreparedStatement pre = conn.prepareStatement(SQL_check);
                ResultSet rs = pre.executeQuery();
                if (rs.next()) 
                {
                    System.out.println("ok");
                    PreparedStatement ps= conn.prepareStatement(trSQL);
                        ps.setString(1, tentau_txt.getText());
                        ps.setString(2, loaitau_txt.getText());
                    int kq = ps.executeUpdate();
                    if (kq == 1) JOptionPane.showMessageDialog(this,"Sửa thành công!");
                    LoadTau();
                }
                else {
                    JOptionPane.showMessageDialog(rootPane,"Không tìm thấy mã tàu! Vui lòng chọn lại!", "Sai định dạng!", HEIGHT);
                }
                    
            } catch (Exception e) {
                e.printStackTrace();
            }
                    
                }
    }//GEN-LAST:event_sua_btActionPerformed

    private void tbtauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtauMouseClicked
        // TODO add your handling code here:
            int indexTB = tbtau.getSelectedRow();
            if(indexTB >=0 && indexTB < tbtau.getRowCount())
            {
                matau_txt.setText(listTau.getValueAt(indexTB,0).toString());
                tentau_txt.setText(listTau.getValueAt(indexTB,1).toString());
                loaitau_txt.setText(listTau.getValueAt(indexTB,2).toString());
            }
    }//GEN-LAST:event_tbtauMouseClicked

    private void xoa_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoa_btActionPerformed
        // TODO add your handling code here:
                if (tentau_txt.getText().equals("")
                || loaitau_txt.getText().equals("")
                || matau_txt.getText().equals("")
            ){
            JOptionPane.showMessageDialog(rootPane,"Thiếu thông tin! Không thể xóa! Vui lòng chọn thông tin", "Thiếu thông tin", HEIGHT);
            matau_txt.setText("");
            tentau_txt.setText("");
            loaitau_txt.setText("");
            }       
         else if (!loaitau_txt.getText().matches("-?\\d+")
                 ) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn lại thông tin!", "Sai định dạng!", HEIGHT);
            matau_txt.setText("");
            tentau_txt.setText("");
            loaitau_txt.setText("");
         }
        else {
            try {
                Connection conn = OracleConnection.getOracleConnection();
                String SQL_check = "select*from TAU where MATAU ='" + matau_txt.getText() + "' AND TENTAU='"+tentau_txt.getText()+"' AND LOAITAU='"+loaitau_txt.getText()+"'";
                String trSQL = "DELETE FROM TAU where MATAU=?";
                PreparedStatement pre = conn.prepareStatement(SQL_check);
                ResultSet rs = pre.executeQuery();
                if (rs.next()) 
                {
                    System.out.println("ok");
                    PreparedStatement ps= conn.prepareStatement(trSQL);
                        ps.setString(1, matau_txt.getText());
                    int kq = ps.executeUpdate();
                    if (kq == 1) JOptionPane.showMessageDialog(this,"Xóa thành công!");
                    LoadTau();
                }
                else {
                    JOptionPane.showMessageDialog(rootPane,"Không tìm thấy tàu! Vui lòng chọn lại!", "Sai định dạng!", HEIGHT);
                matau_txt.setText("");
                tentau_txt.setText("");
                loaitau_txt.setText("");
                }
                    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,e, "Lỗi!", HEIGHT);
            }
                    
                }
    }//GEN-LAST:event_xoa_btActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TrangChu_Admin_fr();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        listTau = (DefaultTableModel) tbtau.getModel();
        listTau.setRowCount(0);
        String tracuu = '%'+txtTraCuu.getText()+'%';
        if(tracuu.equals("")){
            JOptionPane.showMessageDialog(null, "Không có thông tin!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        OracleConnection OC = new OracleConnection();
        Connection conn = null;
        try{
            conn = OC.getOracleConnection();
            String SQL = "SELECT * FROM TAU WHERE MATAU LIKE ? OR TENTAU LIKE ?";
            PreparedStatement pres = conn.prepareStatement(SQL);
            pres.setString(1, tracuu);
            pres.setString(2, tracuu);
            ResultSet rs = pres.executeQuery();
            while(rs.next()){
                String matau= rs.getString("MATAU");
                String tentau = rs.getString("TENTAU");
                String loaitau = rs.getString("LOAITAU");
                listTau.addRow(new Object[] {matau,tentau,loaitau});
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtTraCuu.setText("");
        listTau.setRowCount(0);
        LoadTau();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        matau_txt.setText("");
        tentau_txt.setText("");
        loaitau_txt.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void loaitau_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaitau_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loaitau_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLTau_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLTau_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLTau_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLTau_fr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLTau_fr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField loaitau_txt;
    private javax.swing.JTextField matau_txt;
    private javax.swing.JButton sua_bt;
    private javax.swing.JTable tbtau;
    private javax.swing.JTextField tentau_txt;
    private javax.swing.JButton them_bt;
    private javax.swing.JTextField txtTraCuu;
    private javax.swing.JButton xoa_bt;
    // End of variables declaration//GEN-END:variables
}
