/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import ConnectDB.OracleConnection;
import Resouces.ReportViewer;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.*;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.jdbc.JDBCCategoryDataset;
import javax.swing.DefaultComboBoxModel;
import java.util.HashMap;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author TIEN NHAN
 */
public class ThongKe extends javax.swing.JFrame {

    private Date datenow;
    DefaultTableModel dtmVe;
    DefaultTableModel dtmTuyen;
    public ArrayList<String> listmaG = new ArrayList<String>();
    public ArrayList<String> listtenG = new ArrayList<String>();
    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        dtmVe = (DefaultTableModel) tbVe.getModel();
        dtmTuyen = (DefaultTableModel) tb_dt_tuyen.getModel();
        loadGa();
        setVisible(true);
    }
    
    public String getTenGa(String maga){
        String tenGa = "";
        OracleConnection OC = new OracleConnection();
        try{
            Connection conn = OC.getOracleConnection();
            String sql = "SELECT TENGA FROM GA WHERE MAGA = ?";
            PreparedStatement pres = conn.prepareStatement(sql);
            pres.setString(1, maga);
            ResultSet rs = pres.executeQuery();
            if(rs.next()){
                tenGa = rs.getString(1);
            } 
        }catch(Exception e){
            e.printStackTrace();
        }
        return tenGa;
    }
    
    public void loadGa(){
        OracleConnection OC = new OracleConnection();
        Connection conn = null;
        try{
            conn = OC.getOracleConnection();
            String SQL = "SELECT * FROM GA";
            Statement pres = conn.createStatement();
            ResultSet rs = pres.executeQuery(SQL);
            while(rs.next()){
                listmaG.add(rs.getString("maGa"));
                listtenG.add(rs.getString("TenGa"));
            }
            cbgaDi.setModel(new DefaultComboBoxModel(listtenG.toArray()));
            cbgaDen.setModel(new DefaultComboBoxModel(listtenG.toArray()));
        }catch (Exception e){
            e.printStackTrace();
        }
        datenow = new java.sql.Date(jDateChooser1.getDate().getTime());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVe = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        loc_Ve = new javax.swing.JButton();
        xuat_Ve = new javax.swing.JButton();
        pn_thongke_Ve = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_dt_tuyen = new javax.swing.JTable();
        loc_tuyen = new javax.swing.JButton();
        xuat_tuyen = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTongDT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTongDT1 = new javax.swing.JTextField();
        pn_thongke_dt_tuyen = new javax.swing.JPanel();
        cbgaDi = new javax.swing.JComboBox<>();
        cbgaDen = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thống kê");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thống kê số vé bán được ");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Thống kê");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 31, 263, -1));

        tbVe.setBackground(new java.awt.Color(204, 204, 255));
        tbVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ngày bán ", "Số lượng vé", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(tbVe);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 159, 546, 194));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Từ:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 112, 37, 29));

        jDateChooser1.setMinimumSize(new java.awt.Dimension(130, 22));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 112, 182, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Đến:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 112, 37, 22));

        jDateChooser2.setMinimumSize(new java.awt.Dimension(130, 22));
        jDateChooser2.setPreferredSize(new java.awt.Dimension(130, 22));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 171, 30));

        loc_Ve.setBackground(new java.awt.Color(0, 255, 255));
        loc_Ve.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        loc_Ve.setForeground(new java.awt.Color(255, 0, 153));
        loc_Ve.setText("Lọc");
        loc_Ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loc_VeActionPerformed(evt);
            }
        });
        getContentPane().add(loc_Ve, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 112, 71, -1));

        xuat_Ve.setBackground(new java.awt.Color(0, 255, 255));
        xuat_Ve.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        xuat_Ve.setForeground(new java.awt.Color(255, 0, 153));
        xuat_Ve.setText("Xuất");
        xuat_Ve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuat_VeActionPerformed(evt);
            }
        });
        getContentPane().add(xuat_Ve, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 159, 71, -1));

        javax.swing.GroupLayout pn_thongke_VeLayout = new javax.swing.GroupLayout(pn_thongke_Ve);
        pn_thongke_Ve.setLayout(pn_thongke_VeLayout);
        pn_thongke_VeLayout.setHorizontalGroup(
            pn_thongke_VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        pn_thongke_VeLayout.setVerticalGroup(
            pn_thongke_VeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        getContentPane().add(pn_thongke_Ve, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 121, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Thống kê doanh thu của một tuyến");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 439, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Từ:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 37, 22));

        jDateChooser3.setMinimumSize(new java.awt.Dimension(130, 22));
        jDateChooser3.setPreferredSize(new java.awt.Dimension(130, 22));
        getContentPane().add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 188, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Đến");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 37, 22));

        jDateChooser4.setMinimumSize(new java.awt.Dimension(130, 22));
        jDateChooser4.setPreferredSize(new java.awt.Dimension(130, 22));
        getContentPane().add(jDateChooser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 178, -1));

        tb_dt_tuyen.setBackground(new java.awt.Color(204, 204, 255));
        tb_dt_tuyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Ngày khởi hành", "Ga khởi hành", "Ga kết thúc", "Số vé bán", "Tổng tiền"
            }
        ));
        jScrollPane2.setViewportView(tb_dt_tuyen);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 573, 739, 162));

        loc_tuyen.setBackground(new java.awt.Color(255, 0, 51));
        loc_tuyen.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        loc_tuyen.setForeground(new java.awt.Color(255, 255, 0));
        loc_tuyen.setText("Lọc");
        loc_tuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loc_tuyenActionPerformed(evt);
            }
        });
        getContentPane().add(loc_tuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 75, -1));

        xuat_tuyen.setBackground(new java.awt.Color(255, 0, 51));
        xuat_tuyen.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        xuat_tuyen.setForeground(new java.awt.Color(255, 255, 0));
        xuat_tuyen.setText("Xuất");
        xuat_tuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuat_tuyenActionPerformed(evt);
            }
        });
        getContentPane().add(xuat_tuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 573, 77, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Tổng doanh thu:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 373, -1, -1));

        txtTongDT.setEditable(false);
        txtTongDT.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        getContentPane().add(txtTongDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 369, 117, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("Tổng doanh thu:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 747, -1, -1));

        txtTongDT1.setEditable(false);
        txtTongDT1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtTongDT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongDT1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtTongDT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 747, 113, -1));

        javax.swing.GroupLayout pn_thongke_dt_tuyenLayout = new javax.swing.GroupLayout(pn_thongke_dt_tuyen);
        pn_thongke_dt_tuyen.setLayout(pn_thongke_dt_tuyenLayout);
        pn_thongke_dt_tuyenLayout.setHorizontalGroup(
            pn_thongke_dt_tuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        pn_thongke_dt_tuyenLayout.setVerticalGroup(
            pn_thongke_dt_tuyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        getContentPane().add(pn_thongke_dt_tuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 380, 250));

        getContentPane().add(cbgaDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 500, 150, -1));

        getContentPane().add(cbgaDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 540, 150, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 51));
        jLabel11.setText("Ga đi:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 43, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Ga đến:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 6, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PIC_ICON/nen_all.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loc_VeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loc_VeActionPerformed
        // TODO add your handling code here:
        Date ngbd, ngkt;
        ngbd = new java.sql.Date(jDateChooser1.getDate().getTime());
        ngkt = new java.sql.Date(jDateChooser2.getDate().getTime());
        if(ngbd.compareTo(ngkt) > 0){
            JOptionPane.showMessageDialog(null, "Ngày bắt đầu phải nhỏ hơn ngày kết thúc!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(ngkt.compareTo(datenow) >= 0){
            JOptionPane.showMessageDialog(null, "Ngày kết thúc phải nhỏ hơn ngày hôm nay!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ngaybd, ngaykt;
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dtmVe = (DefaultTableModel) tbVe.getModel();
        dtmVe.setRowCount(0);
        OracleConnection OC = new OracleConnection();
        try{
            Connection conn = OC.getOracleConnection();
            String SQL = "SELECT NGAYDATVE, COUNT(MAVE) AS SLVE, SUM(TONGTIEN) AS TONGTIEN FROM VE WHERE (NGAYDATVE BETWEEN ? AND ?) GROUP BY NGAYDATVE";
            PreparedStatement pres = conn.prepareStatement(SQL);
            ngaybd = String.valueOf(new java.sql.Date(jDateChooser1.getDate().getTime()));
            ngaykt = String.valueOf(new java.sql.Date(jDateChooser2.getDate().getTime()));
            pres.setDate(1, new java.sql.Date(jDateChooser1.getDate().getTime()));
            pres.setDate(2, new java.sql.Date(jDateChooser2.getDate().getTime()));
            ResultSet rs = pres.executeQuery();
            int stt = 0;
            while(rs.next()){
                stt++;
                dtmVe.addRow(new Object[] {stt,rs.getDate("NGAYDATVE"),rs.getInt("SLVE"),rs.getInt("TONGTIEN")});
                dataset.addValue(rs.getDouble("SLVE"), "Số lượng", rs.getDate("NGAYDATVE"));
            }
            long Tong = 0;
            for(int i = 0; i < dtmVe.getRowCount(); i++){
                Tong = Tong + (int)dtmVe.getValueAt(i, 3);
            }
            txtTongDT.setText(String.valueOf(Tong));
            
            JFreeChart chart = ChartFactory.createBarChart("THỐNG KÊ SỐ VÉ BÁN ĐƯỢC TỪ NGÀY  " + ngaybd +" ĐẾN NGÀY "+ ngaykt, "Ngày", "Số lượng", dataset);
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(pn_thongke_Ve.getWidth(), pn_thongke_Ve.getHeight() - 20));
            pn_thongke_Ve.removeAll();
            pn_thongke_Ve.setLayout(new CardLayout());
            pn_thongke_Ve.add(chartPanel);
            pn_thongke_Ve.revalidate();
            pn_thongke_Ve.repaint();
        } catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_loc_VeActionPerformed

    private void loc_tuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loc_tuyenActionPerformed
        // TODO add your handling code here:
        String ngaybd, ngaykt;
        Date ngbd, ngkt;
        ngbd = new java.sql.Date(jDateChooser1.getDate().getTime());
        ngkt = new java.sql.Date(jDateChooser2.getDate().getTime());
        if(cbgaDi.getSelectedIndex() == cbgaDen.getSelectedIndex()){
            JOptionPane.showMessageDialog(null, "Ga khởi hành và ga kết thúc phải khác nhau!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(ngbd.compareTo(ngkt) > 0){
            JOptionPane.showMessageDialog(null, "Ngày bắt đầu phải nhỏ hơn ngày kết thúc!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dtmTuyen = (DefaultTableModel) tb_dt_tuyen.getModel();
        dtmTuyen.setRowCount(0);
        OracleConnection OC = new OracleConnection();
        try{
            Connection conn = OC.getOracleConnection();
            String SQL = "SELECT LICHTRINH.GAKH, GAKT, TO_CHAR(TGIANKH,'YYYY-MM-DD'), COUNT(VE.MAVE) AS SLVE, SUM(VE.TONGTIEN) AS TONGTIEN FROM LICHTRINH INNER JOIN VE ON LICHTRINH.MALT=VE.MALT "
                    + "WHERE (TGIANKH BETWEEN ? AND ?) AND LICHTRINH.GAKH LIKE ? AND LICHTRINH.GAKT LIKE ? GROUP BY LICHTRINH.GAKH, GAKT, TO_CHAR(TGIANKH,'YYYY-MM-DD')";
            PreparedStatement pres = conn.prepareStatement(SQL);
            ngaybd = String.valueOf(new java.sql.Date(jDateChooser3.getDate().getTime()));
            ngaykt = String.valueOf(new java.sql.Date(jDateChooser4.getDate().getTime()));
            pres.setDate(1, new java.sql.Date(jDateChooser3.getDate().getTime()));
            pres.setDate(2, new java.sql.Date(jDateChooser4.getDate().getTime()));
            pres.setString(3, '%'+listmaG.get(cbgaDi.getSelectedIndex())+'%');
            pres.setString(4, '%'+listmaG.get(cbgaDen.getSelectedIndex())+'%');
            ResultSet rs = pres.executeQuery();
            int stt = 0;
            while(rs.next()){
                stt++;
                dtmTuyen.addRow(new Object[] {stt,rs.getString("TO_CHAR(TGIANKH,'YYYY-MM-DD')"),getTenGa(rs.getString("GAKH")),getTenGa(rs.getString("GAKT")),rs.getInt("SLVE"),rs.getInt("TONGTIEN")});
                dataset.addValue(rs.getDouble("TONGTIEN"), "Doanh thu", getTenGa(rs.getString("GAKH"))+" - "+getTenGa(rs.getString("GAKT"))+" "+rs.getString("TO_CHAR(TGIANKH,'YYYY-MM-DD')"));
            }
            long Tong = 0;
            for(int i = 0; i < dtmTuyen.getRowCount(); i++){
                Tong = Tong + (int)dtmTuyen.getValueAt(i, 5);
            }
            txtTongDT1.setText(String.valueOf(Tong));
            JFreeChart chart = ChartFactory.createBarChart("THỐNG KÊ DOANH THU CỦA TUYẾN CÓ THỜI GIAN KHỞI HÀNH TỪ NGÀY  " + ngaybd +" ĐẾN NGÀY "+ ngaykt, "Tuyến", "Doanh thu", dataset);
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(pn_thongke_dt_tuyen.getWidth(), pn_thongke_dt_tuyen.getHeight() - 20));
            pn_thongke_dt_tuyen.removeAll();
            pn_thongke_dt_tuyen.setLayout(new CardLayout());
            pn_thongke_dt_tuyen.add(chartPanel);
            pn_thongke_dt_tuyen.revalidate();
            pn_thongke_dt_tuyen.repaint();
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_loc_tuyenActionPerformed

    private void txtTongDT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongDT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongDT1ActionPerformed

    private void xuat_VeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuat_VeActionPerformed
        // TODO add your handling code here:
        if(dtmVe.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Không có dữ liệu để xuất!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ngaybd, ngaykt, tongdt;
        ngaybd = String.valueOf(new java.sql.Date(jDateChooser1.getDate().getTime()));
        ngaykt = String.valueOf(new java.sql.Date(jDateChooser2.getDate().getTime()));
        tongdt = txtTongDT.getText();
        try {
                LayThongTinTKVe(ngaybd,ngaykt,tongdt);
            } catch (SQLException | JRException ex) {
                System.out.println(ex);
            }
    }//GEN-LAST:event_xuat_VeActionPerformed

    private void xuat_tuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuat_tuyenActionPerformed
        // TODO add your handling code here:
        if(dtmTuyen.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Không có dữ liệu để xuất !", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ngaybd, ngaykt, tgkh, tgkt, magkh, magkt, tongdt;
        ngaybd = String.valueOf(new java.sql.Date(jDateChooser3.getDate().getTime()));
        ngaykt = String.valueOf(new java.sql.Date(jDateChooser4.getDate().getTime()));
        tgkh = cbgaDi.getSelectedItem().toString();
        tgkt = cbgaDen.getSelectedItem().toString();
        magkh = '%'+listmaG.get(cbgaDi.getSelectedIndex())+'%';
        magkt = '%'+listmaG.get(cbgaDen.getSelectedIndex())+'%';
        tongdt = txtTongDT1.getText();
        try {
                LayThongTinTKTuyen(ngaybd,ngaykt,tgkh,tgkt,magkh,magkt,tongdt);
            } catch (SQLException | JRException ex) {
                System.out.println(ex);
            }
    }//GEN-LAST:event_xuat_tuyenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TrangChu_Admin_fr();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LayThongTinTKVe(String ngaybd, String ngaykt, String tongdt) throws SQLException, JRException {
        // TODO code application logic here
        
        HashMap hs= new HashMap();
        hs.put("ngbd", ngaybd);
        hs.put("ngkt", ngaykt);
        hs.put("tongtien", tongdt);
        String localDir = System.getProperty("user.dir");

        ReportViewer viewer = new ReportViewer(localDir+"\\src\\Resouces\\report_TKSLVE.jrxml",hs);
        viewer.setVisible(true);
    }
    
    private void LayThongTinTKTuyen(String ngaybd, String ngaykt,String tgkh, String tgkt, String magkh, String magkt, String tongdt) throws SQLException, JRException {
        // TODO code application logic here
        
        HashMap hs= new HashMap();
        hs.put("ngbd", ngaybd);
        hs.put("ngkt", ngaykt);
        hs.put("tengkh", tgkh);
        hs.put("tengkt", tgkt);
        hs.put("magakh", magkh);
        hs.put("magakt", magkt);
        hs.put("tongtien", tongdt);
        String localDir = System.getProperty("user.dir");

        ReportViewer viewer = new ReportViewer(localDir+"\\src\\Resouces\\report_TKDT_TUYEN.jrxml",hs);
        viewer.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbgaDen;
    private javax.swing.JComboBox<String> cbgaDi;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loc_Ve;
    private javax.swing.JButton loc_tuyen;
    private javax.swing.JPanel pn_thongke_Ve;
    private javax.swing.JPanel pn_thongke_dt_tuyen;
    private javax.swing.JTable tbVe;
    private javax.swing.JTable tb_dt_tuyen;
    private javax.swing.JTextField txtTongDT;
    private javax.swing.JTextField txtTongDT1;
    private javax.swing.JButton xuat_Ve;
    private javax.swing.JButton xuat_tuyen;
    // End of variables declaration//GEN-END:variables
}
